geomesa/geomesa-geoserver

- geomesa-gs-wfs/pom.xml
- geomesa-gs-wfs/src/main/scala/com/ccri/geomesa/gs/wfs/output/BinaryViewerOutputFormat.scala
This associated GeoMesa ticket moved some files that this module depends on.
> GEOMESA-1865 Refactor bin file computation for common use

- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/BinaryViewerOutputFormat.scala
> Updated package name for QueryPlanner.

- geomesa-gs-styling/README.md
- geomesa-gs-styling/pom.xml
- geomesa-gs-styling/src/main/scala/org/geomesa/gs/styling/GeoMesaMarkFactory.scala
- geomesa-gs-styling/src/main/scala/org/geomesa/gs/styling/filter/GeoMesaFastMark.scala
Signed-off-by: Austin Heyne <aheyne@ccri.com>
> Allowing any input data type for icon heading

- geomesa-gs-avro-mimetype/pom.xml
- geomesa-gs-catalog-listener/pom.xml
- geomesa-gs-kafka-09/pom.xml
- geomesa-gs-kafka-10/pom.xml
- geomesa-gs-security/pom.xml
- geomesa-gs-styling/pom.xml
- geomesa-gs-wfs/pom.xml
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/BinaryViewerOutputFormat.scala
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wps/output/BinaryViewerProcessIO.scala
- pom.xml
> Bumping geomesa version to 1.3.3

- pom.xml
> Pom.xml updates required for publishing to Maven Central.

- geomesa-gs-avro-mimetype/pom.xml
- geomesa-gs-catalog-listener/pom.xml
- geomesa-gs-kafka-09/pom.xml
- geomesa-gs-kafka-10/pom.xml
- geomesa-gs-security/pom.xml
- geomesa-gs-styling/pom.xml
- geomesa-gs-wfs/pom.xml
- pom.xml
Signed-off-by: Matt Williams <mcw8d@ccri.com>
> Bumping GeoMesa version to 1.3.4-SNAPSHOT

- geomesa-gs-styling/src/main/scala/org/geomesa/gs/styling/filter/GeoMesaLabelParser.scala
Signed-off-by: Austin Heyne <aheyne@ccri.com>
> Only attempt to parse labels if it contains a period.

- geomesa-gs-avro-mimetype/pom.xml
- geomesa-gs-catalog-listener/pom.xml
- geomesa-gs-kafka-09/pom.xml
- geomesa-gs-kafka-10/pom.xml
- geomesa-gs-security/pom.xml
- geomesa-gs-styling/pom.xml
- geomesa-gs-wfs/pom.xml
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
- pom.xml
Corresponds with https://github.com/locationtech/geomesa/pull/1759
> 1.3 - GEOMESA-2075 Single pass arrow scan

- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
Corresponds to https://github.com/locationtech/geomesa/pull/1764
> GEOMESA-2075 Single pass arrow scan

- geomesa-gs-avro-mimetype/pom.xml
- geomesa-gs-catalog-listener/pom.xml
- geomesa-gs-kafka-09/pom.xml
- geomesa-gs-kafka-10/pom.xml
- geomesa-gs-security/pom.xml
- geomesa-gs-styling/pom.xml
- geomesa-gs-wfs/pom.xml
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/BinaryViewerOutputFormat.scala
- pom.xml
> 1.3 - GEOMESA-2139,GEOMESA-2156 Adding full options and pre-sorting to WFS arrow queries

- geomesa-gs-wfs/pom.xml
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/BinaryViewerOutputFormat.scala
> GEOMESA-2139,GEOMESA-2156 Adding full options and pre-sorting to WFS arrow queries

- geomesa-gs-raster/README.md
- geomesa-gs-raster/pom.xml
- geomesa-gs-raster/src/main/resources/applicationContext.xml
- geomesa-gs-raster/src/main/resources/org/geomesa/gs/wcs/GeoMesaCoverageStoreEditPanel.html
- geomesa-gs-raster/src/main/scala/org/geomesa/gs/GeoMesaStoreEditPanel.scala
- geomesa-gs-raster/src/main/scala/org/geomesa/gs/wcs/GeoMesaCoverageStoreEditPanel.scala
- pom.xml
> Porting raster plugin from community module

- geomesa-gs-raster/README.md
- geomesa-gs-raster/pom.xml
- geomesa-gs-raster/src/main/resources/applicationContext.xml
- geomesa-gs-raster/src/main/resources/org/geomesa/gs/wcs/GeoMesaCoverageStoreEditPanel.html
- geomesa-gs-raster/src/main/scala/org/geomesa/gs/GeoMesaStoreEditPanel.scala
- geomesa-gs-raster/src/main/scala/org/geomesa/gs/wcs/GeoMesaCoverageStoreEditPanel.scala
- pom.xml
> 1.3 - Porting raster plugin from community module

- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
> GEOMESA-2184 Passing Arrow proxyId flag through WFS query

- geomesa-gs-catalog-listener/src/main/scala/org/geomesa/gs/catalog/GeoMesaCatalogListener.scala
- pom.xml
> GEOMESA-2803 Upgrade to GeoTools 23.0

- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/AvroOutputFormat.scala
- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/BinaryViewerOutputFormat.scala
> Implement getCapabilitiesElementName

- geomesa-gs-wfs/src/main/resources/GeoServerApplication.properties
> GEOMESA-2946 Adding Arrow labels to GeoServer properties file.

- geomesa-gs-kafka-catalog-listener/README.md
- geomesa-gs-kafka-catalog-listener/pom.xml
- geomesa-gs-kafka-catalog-listener/src/main/resources/applicationContext.xml
- geomesa-gs-kafka-catalog-listener/src/main/scala/org/geomesa/gs/catalog/kafka/GeoMesaKafkaCatalogListener.scala
- geomesa-gs-kafka-catalog-listener/src/main/scala/org/geomesa/gs/rest/kafka/KafkaLoaderStatusController.scala
Signed-off-by: Jim Hughes <jhughes@ccri.com>
> GEOMESA-3048 Add readiness check for Kafka DataStore Initial Loads

- geomesa-gs-monitor-elasticsearch/pom.xml
- geomesa-gs-monitor-elasticsearch/src/main/resources/applicationContext.xml
- geomesa-gs-monitor-elasticsearch/src/main/scala/org/geomesa/gs/monitor/elastic/ElasticRequestDataListener.scala
- geomesa-gs-monitor-elasticsearch/src/main/scala/org/geomesa/gs/monitor/elastic/ExtendedRequestData.scala
- geomesa-gs-monitor-elasticsearch/src/test/scala/org/geomesa/gs/monitor/elastic/ExtendedRequestDataTest.scala
> GEOMESA-3188 Extend ElasticSearch data model to include the resource datastore

- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
- pom.xml
See Co-MR - https://github.com/locationtech/geomesa/pull/3128
> GEOMESA-3362 Adds optional flattened arrow output

- geomesa-gs-wfs/src/main/scala/org/geomesa/gs/wfs/output/ArrowOutputFormat.scala
[GEOMESA-3401](https://geomesa.atlassian.net/browse/GEOMESA-3401)
- Aggregated status changed to be set based on `SimpleFeatureTypes.compare(sft1, sft2)` instead of SFT equality
> GEOMESA-3401: Apache Arrow format encoding for WFS 1.1.0 and 2.0.0 requests
